### ISSUE TITLE
Edits to education page - Classroom Tab

### ISSUE THREAD

**Issue by kellinora** [zooniverse/Planet-Hunters-2#267]
Change title of tab to Other Classroom Resources

Updated text for: What resources are available for the classroom?
Here are some resources that can be great tools for introducing students to Planet Hunters. 
NASA Kepler Missions website: http://kepler.nasa.gov
NASA Planet Quest website: http://planetquest.jpl.nasa.gov
Exoplanet Transit Simulator by The Astronomy Department at University of Nebraska
National Science Foundation's Science Behind The News: Extrasolar Planets, describes the Transit and Doppler methods.
Educator Resource Guide provided by NASA: Astrobiology in Your Classroom, Life on Earth …and elsewhere?
Our Place in Space activities produced by the Lunar and Planetary Institute

**Comment by kellinora** [comment]
@saschaishikawa  @JulieAnnKU Looks good except that the tutorial video has been replaced with what looks like a Google Forms notification.  Julie probably has the correct tutorial video file.
![screen shot 2015-07-01 at 1 31 34 pm](https://cloud.githubusercontent.com/assets/1483785/8461924/9ac19828-1ff5-11e5-94eb-b78a23936f85.png)

**Comment by kellinora** [comment]
Weird.  I just refreshed the page and the video is back.  Huzzah!

**Comment by saschaishikawa** [comment]
Cool. I'm gonna close this issue then.
