### ISSUE TITLE
Long period acknowledgements page has gone missing

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Planet-Hunters-2#270]
Should be straightforward to transfer

**Comment by astopy** [comment]
I don't understand what's missing...

There's this page which is still live: http://www.planethunters.org/#/acknowledgements  is there supposed to be something else somewhere?

**Comment by chrislintott** [comment]
@astopy In this paper : http://arxiv.org/abs/1310.5912 

We link to a page: http://www.planethunters.org/PH6 which seems to have gone missing.

**Comment by astopy** [comment]
Ah! That’s on old.planethunters.org <http://old.planethunters.org/>. I’ll set up a redirect.
