### ISSUE TITLE
Can't higlight - nothing happens on click.

### ISSUE THREAD

**Issue by manzare** [zooniverse/Planet-Hunters-2#275]
"Do you see a transit?
If so, highlight it on the light curve below!"
--- Except that no matter where I click on it doesn't highlight. Nothing happens when I click around. That's weird because when I log and do the tutorial highlighting works, it's just it stops working when I go to "classify".
I encountered the same error both on Mac and Windows.

**Comment by astopy** [comment]
@manzare Could you let me know which web browser you're using?

**Comment by manzare** [comment]
On mac I tried it under Chrome and FFox, on Windows I used FFox. Clicking and highlighting doesn't work on any of these browsers after the first few screens. It means I can highlight in the first few simulations, then it just stops working.

Note: I'm still on the simulated classifying.

**Comment by astopy** [comment]
@manzare I know it's been a while, but I wanted to check if this is still an issue for you? I suspect this might have been the same problem as #276 which was fixed in July.

**Comment by astopy** [comment]
Closing this for now. Please let me know if I should re-open.
